_wandb:
    value:
        cli_version: 0.19.7.dev1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7.dev1
            "8":
                - 5
            "10":
                - 3
            "12": 0.19.7.dev1
            "13": linux-x86_64
batch_size:
    value: 64
beam_size:
    value: 5
cell_type:
    value: GRU
decoder_layers:
    value: 2
dropout:
    value: 0.3
embed_dim:
    value: 64
encoder_layers:
    value: 3
epochs:
    value: 10
hidden_dim:
    value: 256
lr:
    value: 0.001
max_len:
    value: 32
