wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 5
cell_type:
  value: LSTM
decoder_layers:
  value: 1
dropout:
  value: 0.3
embed_dim:
  value: 32
encoder_layers:
  value: 3
epochs:
  value: 10
hidden_dim:
  value: 256
lr:
  value: 0.001
max_len:
  value: 32
