wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 5
cell_type:
  value: LSTM
decoder_layers:
  value: 3
dropout:
  value: 0.2
embed_dim:
  value: 16
encoder_layers:
  value: 3
epochs:
  value: 10
hidden_dim:
  value: 32
lr:
  value: 0.001
max_len:
  value: 32
